server:
  port: 3000
spring:
  redis:
    host: 192.168.136.212
  application:
    name: kjq-crowd-redis
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include= *: