server:
  port: 2000
spring:
  application:
    name: kjq-crowd-mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_crowd?serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include= *:
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.crowd.mapper.MemberPOMapper

logging:
  level:
    com.atguigu.crowd.mapper: debug
    com.atguigu.crowd.test: debug